name: Build RSDKv5

on: workflow_dispatch

# each artifact is like 15MB so we'll start by only doing it manually
# on:
#   push:
#     branches:
#       - master

# TODO: readd with: submodules: recursive once we can

jobs:
  build-a30:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: setup-toolchain
      run: |
        sudo apt update
        sudo apt-get install build-essential make cmake wget autogen autoconf automake build-essential libogg-dev libogg libc6 libc6-dev libsdl2-dev libtheora-dev libglew-dev libglfw3-dev libjack-dev -y
        wget -q https://github.com/steward-fu/website/releases/download/miyoo-a30/a30_toolchain-v1.0.tar.gz
        tar xzf a30_toolchain-v1.0.tar.gz -C /opt/
        chmod +x /opt/a30/bin/*
    - name: make
      run: |
        export PATH=/opt/a30/bin/:$PATH
        export CROSS_COMPILE=/opt/a30/bin/arm-a30-linux-gnueabihf-
        export PREFIX=/usr
        export PKG_CONFIG_PATH=/opt/a30/lib/pkgconfig/:/usr/local/lib/pkgconfig/
        export CC="arm-a30-linux-gnueabihf-gcc"
        export CXX="arm-a30-linux-gnueabihf-g++"
        make -j4 RSDK_ONLY=1 SUBSYSTEM=SDL2 AUTOBUILD=1
        make -j4 clean-rsdk
        make -j4 RSDK_ONLY=1 SUBSYSTEM=SDL2 RSDK_REVISION=3 AUTOBUILD=1
    - name: output
      run: |
        cat config.log
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: a30-linux
        path: bin/Linux

